import type { Metadata } from 'next'
import './globals.css'
import { Nunito_Sans } from 'next/font/google'
import Header from './components/header'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export const nunito = Nunito_Sans({ subsets: ['latin'] })

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={nunito.className}>
        <Header>{children}</Header>
      </body>
    </html>
  )
}
